services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - AES_KEY_TOTP=${AES_KEY_TOTP}
      - AES_KEY_RSA=${AES_KEY_RSA}
      - AES_KEY_NOTE=${AES_KEY_NOTE}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - ./instance:/app/instance