services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - AES_KEY_TOTP=${AES_KEY_TOTP}
      - AES_KEY_RSA=${AES_KEY_RSA}
      - AES_KEY_NOTE=${AES_KEY_NOTE}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - ./instance:/app/instance
  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/safenotes.crt:/etc/nginx/safenotes.crt:ro
      - ./docker/nginx/safenotes.key:/etc/nginx/safenotes.key:ro
      - ./notes/static:/app/notes/static:ro
