"""Add TOTP secret to user model

Revision ID: 08293801416a
Revises: 2a82499ad7ce
Create Date: 2024-12-24 21:51:09.163915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08293801416a'
down_revision = '2a82499ad7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
