"""Add rsa keys to User

Revision ID: 2ab11eb89d7d
Revises: 60adc77b3e05
Create Date: 2025-01-01 22:11:58.265640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab11eb89d7d'
down_revision = '60adc77b3e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('public_key', sa.Text(), nullable=True))
        batch_op.alter_column('totp_secret',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.drop_column('public_key')
        batch_op.drop_column('private_key')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
