"""Add shared notes table

Revision ID: 60adc77b3e05
Revises: d14d21d99025
Create Date: 2024-12-31 15:40:28.655877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60adc77b3e05'
down_revision = 'd14d21d99025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_notes')
    # ### end Alembic commands ###
